export const inventoryItems = [
  {
    invInfoId: 1,
    sku: "ELEC-001",
    particular: "Electricity",
    qty: 10,
    unit_cp: 15.99,
    unit_sp: 2489.99,
    amt: 0,
  },
  {
    invInfoId: 2,
    sku: "CLTH-045",
    particular: "Clothing",
    qty: 25,
    unit_cp: 8.5,
    unit_sp: 19.99,
    amt: 0,
  },
  {
    invInfoId: 3,
    sku: "HOME-112",
    particular: "Home",
    qty: 5,
    unit_cp: 45.75,
    unit_sp: 89.99,
    amt: 0,
  },
  {
    invInfoId: 4,
    sku: "TOOL-208",
    particular: "Tool",
    qty: 8,
    unit_cp: 22.4,
    unit_sp: 39.99,
    amt: 0,
  },
  {
    invInfoId: 5,
    sku: "ELEC-001",
    particular: "Electricity",
    qty: 10,
    unit_cp: 15.99,
    unit_sp: 29.99,
    amt: 0,
  },
];
